#!/usr/bin/env python3
"""Build `learn.app` and `Stop learn.app` in ~/Applications.

    python3 tools/make_mac_app.py

Double-clicking `learn.app` starts the server if it is not running (in the
background, logging to `.cache/learn.log`) and opens the browser; if it is
already running it just opens the browser. `Stop learn.app` shuts it down.
Re-run this script after moving the project folder or changing the uv path.
"""

from __future__ import annotations

import os
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]
APPS = Path.home() / "Applications"
UV = shutil.which("uv") or str(Path.home() / ".local/bin/uv")
URL = "http://127.0.0.1:8765"

LAUNCH = f"""#!/bin/bash
# Generated by tools/make_mac_app.py — starts learn if needed, then opens it.
PROJECT="{PROJECT}"
UV="{UV}"
URL="{URL}"
if curl -s -m 1 "$URL/api/health" >/dev/null 2>&1; then
  open "$URL/"
  exit 0
fi
cd "$PROJECT" || {{ osascript -e 'display alert "learn" message "Project folder not found: {PROJECT}"'; exit 1; }}
mkdir -p .cache
BROWSER=none nohup "$UV" run learn >> .cache/learn.log 2>&1 &
for _ in $(seq 1 60); do
  curl -s -m 1 "$URL/api/health" >/dev/null 2>&1 && break
  sleep 0.5
done
if curl -s -m 1 "$URL/api/health" >/dev/null 2>&1; then
  open "$URL/"
else
  osascript -e 'display alert "learn" message "The server did not start. See .cache/learn.log in the project folder."'
fi
"""

STOP = """#!/bin/bash
# Generated by tools/make_mac_app.py — stops the learn server on port 8765.
PIDS=$(lsof -nP -tiTCP:8765 -sTCP:LISTEN 2>/dev/null)
if [ -z "$PIDS" ]; then
  osascript -e 'display notification "learn was not running" with title "learn"'
  exit 0
fi
kill $PIDS 2>/dev/null
osascript -e 'display notification "learn stopped" with title "learn"'
"""


def bundle(name: str, script: str, icon: Path | None) -> Path:
    app = APPS / f"{name}.app"
    if app.exists():
        shutil.rmtree(app)
    macos = app / "Contents" / "MacOS"
    res = app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    res.mkdir(parents=True)
    exe = macos / "launcher"
    exe.write_text(script)
    exe.chmod(0o755)
    info = {
        "CFBundleName": name,
        "CFBundleDisplayName": name,
        "CFBundleIdentifier": f"local.learn.{name.replace(' ', '-').lower()}",
        "CFBundleVersion": "1.0",
        "CFBundleShortVersionString": "1.0",
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": "launcher",
        "LSUIElement": True,  # no Dock bounce: the launcher exits once the browser opens
        "LSMinimumSystemVersion": "12.0",
    }
    if icon and icon.exists():
        shutil.copy(icon, res / "learn.icns")
        info["CFBundleIconFile"] = "learn.icns"
    with (app / "Contents" / "Info.plist").open("wb") as f:
        plistlib.dump(info, f)
    return app


def build_icon(variant: str = "") -> Path | None:
    """Render tools/icon.html with the project's Playwright, then pack an .icns.

    `variant="stop"` renders the red-bordered icon for `Stop learn.app`.
    """
    out = PROJECT / ".cache" / "icon"
    out.mkdir(parents=True, exist_ok=True)
    suffix = f"-{variant}" if variant else ""
    png = out / f"icon{suffix}-1024.png"
    if not (PROJECT / "web" / "node_modules" / "playwright").exists():
        print("Playwright not found under web/node_modules; skipping the icon.")
        return None
    subprocess.run(
        ["node", str(PROJECT / "tools" / "icon.mjs"), str(png), variant],
        check=True,
        cwd=PROJECT / "web",
    )
    iconset = out / f"learn{suffix}.iconset"
    if iconset.exists():
        shutil.rmtree(iconset)
    iconset.mkdir()
    for size in (16, 32, 128, 256, 512):
        for scale in (1, 2):
            px = size * scale
            name = f"icon_{size}x{size}{'@2x' if scale == 2 else ''}.png"
            subprocess.run(
                ["sips", "-z", str(px), str(px), str(png), "--out", str(iconset / name)],
                check=True, capture_output=True,
            )
    icns = out / f"learn{suffix}.icns"
    subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(icns)], check=True)
    return icns


def main() -> int:
    if sys.platform != "darwin":
        print("This builds a macOS app bundle; run it on the Mac.")
        return 1
    APPS.mkdir(exist_ok=True)
    icon = build_icon()
    stop_icon = build_icon("stop")
    app = bundle("learn", LAUNCH, icon)
    stop = bundle("Stop learn", STOP, stop_icon)
    # Refresh Finder's icon cache for the new bundles.
    for a in (app, stop):
        os.utime(a, None)
    print(f"Built:\n  {app}\n  {stop}\nuv: {UV}\nProject: {PROJECT}")
    print("Drag learn.app to the Dock if you want it there.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
